# -*- coding: utf-8 -*-
"""advanced_name_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBy9wXrB8Ne3tA2ZDK1Pf9x5yEcdE6Cj
"""

"""
高级人名清洗专家系统 (Pro Ver.)
支持基于拼音相似度的同音异形字和错别字的聚类与交互式修正
"""

import pandas as pd
import numpy as np
from collections import defaultdict
import warnings
import difflib
from pypinyin import lazy_pinyin, Style

# 可选美化库
try:
    from tabulate import tabulate
    HAS_TABULATE = True
except ImportError:
    HAS_TABULATE = False

try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

warnings.filterwarnings('ignore')


class AdvancedNameCleaner:
    """
    高级人名清洗专家系统

    Parameters
    ----------
    aux_columns : list, optional
        辅助列名称列表，用于在决策时展示更多上下文信息（如w_name, year, post1, distname20等）
    threshold : float, default=0.3
        拼音相似度阈值，高于此值视为疑似同音变体
    """

    def __init__(self, aux_columns=None, threshold=0.3):
        self.aux_columns = aux_columns if aux_columns else []
        self.threshold = threshold
        self.name_info_cache = {}

    def _get_pinyin_str(self, name):
        """获取名字的拼音字符串（带声调）"""
        if pd.isna(name):
            return ""
        name = str(name).strip()
        if name in self.name_info_cache:
            return self.name_info_cache[name]
        pys = lazy_pinyin(name, style=Style.TONE3, errors='ignore')
        pinyin_str = "".join(pys)
        self.name_info_cache[name] = pinyin_str
        return pinyin_str

    def calculate_similarity(self, name1, name2):
        """计算两个名字的拼音相似度"""
        py1 = self._get_pinyin_str(name1)
        py2 = self._get_pinyin_str(name2)
        if py1 == py2:
            return 1.0
        return difflib.SequenceMatcher(None, py1, py2).ratio()

    def find_potential_groups(self, df, name_col='p_name'):
        """
        基于拼音相似度聚类，返回候选分组列表

        Returns
        -------
        list of list
            每个子列表是一组疑似同音的名字
        """
        print(f"正在扫描 {len(df)} 条数据，构建拼音指纹...")

        unique_names = df[name_col].dropna().unique()
        surname_blocks = defaultdict(list)
        for name in unique_names:
            if not str(name).strip():
                continue
            surname = str(name)[0]
            surname_blocks[surname].append(name)

        potential_groups = []

        iterator = surname_blocks.items()
        if HAS_TQDM:
            iterator = tqdm(iterator, desc="聚类分析中", unit="block")

        for surname, names in iterator:
            if len(names) < 2:
                continue

            # 并查集合并相似名字
            parent = {n: n for n in names}

            def find(i):
                if parent[i] != i:
                    parent[i] = find(parent[i])
                return parent[i]

            def union(i, j):
                root_i = find(i)
                root_j = find(j)
                if root_i != root_j:
                    parent[root_j] = root_i

            has_match = False
            names_list = list(names)
            for i in range(len(names_list)):
                for j in range(i + 1, len(names_list)):
                    n1, n2 = names_list[i], names_list[j]
                    sim = self.calculate_similarity(n1, n2)
                    # 相似度达标且长度差不超过1（避免“张三丰”和“张三”误判）
                    if sim >= self.threshold and abs(len(n1) - len(n2)) <= 1:
                        union(n1, n2)
                        has_match = True

            if has_match:
                groups = defaultdict(list)
                for n in names:
                    groups[find(n)].append(n)
                for root, members in groups.items():
                    if len(members) > 1:
                        potential_groups.append(members)

        # 排序：优先处理成员多、名字长的复杂组
        potential_groups.sort(key=lambda x: (len(x), len(x[0])), reverse=True)
        return potential_groups

    def _display_group_context(self, df, name_col, name_group):
        """展示一个分组的上下文信息（频次、辅助列等）"""
        records = df[df[name_col].isin(name_group)].copy()
        summary_data = []

        for name in name_group:
            sub_df = records[records[name_col] == name]
            count = len(sub_df)
            pinyin = self._get_pinyin_str(name)

            row = {
                "ID": "",
                "名字": name,
                "频次": count,
                "拼音": pinyin
            }

            # 辅助列展示
            for col in self.aux_columns:
                if col in df.columns:
                    unique_vals = sub_df[col].dropna().unique()
                    unique_vals = [str(v) for v in unique_vals if str(v).strip() != '']
                    val_str = ",".join(unique_vals)
                    # 针对单位名称特殊处理，允许更长显示
                    limit = 40 if 'w_name' in col else 15
                    if len(val_str) > limit:
                        val_str = val_str[:limit-3] + "..."
                    row[col] = val_str if val_str else "-"
                else:
                    row[col] = "N/A"

            summary_data.append(row)

        summary_data.sort(key=lambda x: x["频次"], reverse=True)
        for idx, row in enumerate(summary_data):
            row["ID"] = idx + 1

        print("\n" + "=" * 100)
        print(f"【疑似混淆分组】 发现 {len(name_group)} 个变体")

        if HAS_TABULATE:
            print(tabulate(summary_data, headers="keys", tablefmt="grid"))
        else:
            # 降级显示
            header = f"{'ID':<4} {'名字':<8} {'频次':<6} " + " ".join([f"{c:<15}" for c in self.aux_columns])
            print(header)
            for row in summary_data:
                line = f"{row['ID']:<4} {row['名字']:<8} {row['频次']:<6} "
                for col in self.aux_columns:
                    line += f"{str(row[col]):<15} "
                print(line)

        return summary_data

    def interactive_review(self, df, name_col='p_name'):
        """
        启动交互式审查，返回清洗后的DataFrame和修正映射字典

        Returns
        -------
        df_result : pd.DataFrame
            清洗后的数据，会新增一列 '{name_col}_raw' 保存原始值
        correction_map : dict
            修正映射 {原始名: 标准名}
        """
        # 验证辅助列
        valid_aux = []
        for col in self.aux_columns:
            if col in df.columns:
                valid_aux.append(col)
            else:
                print(f"警告: 数据集中未找到列 '{col}'，将忽略此辅助列。")
        self.aux_columns = valid_aux

        groups = self.find_potential_groups(df, name_col)

        if not groups:
            print("未发现疑似混淆的人名。")
            return df, {}

        print(f"\n>>> 扫描完成！共发现 {len(groups)} 组疑似混淆的名字。")
        print(f">>> 当前辅助决策维度: {self.aux_columns}")

        correction_map = {}

        for i, group in enumerate(groups):
            # 跳过已处理的名字（避免重复）
            if any(n in correction_map for n in group):
                continue

            print(f"\n>>> 进度: {i+1}/{len(groups)}")
            summary = self._display_group_context(df, name_col, group)
            name_list = [row['名字'] for row in summary]

            print("\n指令:")
            print("  [ID]      : 全组合并（如输入 1，则其他人名都改为第1个）")
            print("  pass / p  : 跳过（不同人）")
            print("  custom / c: 自定义（如 '2>1' 表示把2改为1）")
            print("  stop / q  : 保存并退出")

            choice = input("指令 > ").strip().lower()

            if choice in ['stop', 'q', 'quit']:
                break
            elif choice in ['pass', 'p', '']:
                continue
            elif choice.isdigit():
                idx = int(choice) - 1
                if 0 <= idx < len(name_list):
                    target_name = name_list[idx]
                    for n in name_list:
                        if n != target_name:
                            correction_map[n] = target_name
                    print(f">> 已合并为: {target_name}")
                else:
                    print("无效ID，跳过")
            elif choice in ['custom', 'c']:
                sub_cmd = input("输入映射（如 2>1; 3>1） > ").strip()
                try:
                    pairs = sub_cmd.split(';')
                    for pair in pairs:
                        if '>' not in pair:
                            continue
                        src_idx, tgt_idx = map(int, pair.split('>'))
                        src_name = name_list[src_idx-1]
                        tgt_name = name_list[tgt_idx-1]
                        correction_map[src_name] = tgt_name
                        print(f"   {src_name} -> {tgt_name}")
                except Exception:
                    print("指令格式错误，跳过。")
            else:
                print("未知指令，跳过")

        # 应用修正
        print("\n" + "=" * 80)
        print(f"正在应用 {len(correction_map)} 条修正...")

        df_result = df.copy()
        # 保留原始人名列
        raw_col = f'{name_col}_raw'
        if raw_col not in df_result.columns:
            df_result[raw_col] = df_result[name_col]

        df_result[name_col] = df_result[name_col].replace(correction_map)

        return df_result, correction_map
