# -*- coding: utf-8 -*-
"""example_usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVrdMSPpcJ24cQnkZp-MXMH0ipaw09iM
"""

"""
演示如何使用 AdvancedNameCleaner 清洗人名同音异形字
"""

import pandas as pd
from advanced_name_cleaner import AdvancedNameCleaner

# ---------- 1. 构造模拟数据 ----------
data = {
    'p_name': [
        '王俊峰', '王俊峰', '王俊峰', '王俊峰', '王俊峰',
        '王俊锋', '王俊锋',
        '王俊峰', '王俊峰', '王俊峰', '李明'
    ],
    'year': [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2017],
    'post1': [
        '副市长', '副市长', '副市长', '副市长', '副市长',
        '副市长', '副市长',
        '副市长', '副市长', '副市长', '局长'
    ],
    'company': [
        '甲市人民政府', '甲市人民政府', '甲市人民政府',
        '甲市人民政府', '甲市人民政府',
        '甲市人民政府', '甲市人民政府',
        '甲市人民政府', '甲市人民政府', '甲市人民政府',
        '乙市财政局'
    ]
}

df_combined = pd.DataFrame(data)
print("原始数据：")
print(df_combined)

# ---------- 2. 初始化清洗器（指定辅助列） ----------
cleaner = AdvancedNameCleaner(
    aux_columns=['year', 'post1', 'company'],
    threshold=0.85
)

# ---------- 3. 启动交互式清洗 ----------
df_final, mapping = cleaner.interactive_review(df_combined, name_col='p_name')

# ---------- 4. 输出结果 ----------
print("\n" + "=" * 80)
print("清洗完成！修正映射如下：")
for k, v in mapping.items():
    print(f"  '{k}' -> '{v}'")

print("\n清洗后的数据：")
print(df_final)