# -*- coding: utf-8 -*-
"""example_usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVrdMSPpcJ24cQnkZp-MXMH0ipaw09iM
"""

"""
演示如何使用 AdvancedNameCleaner 清洗人名同音异形字
"""

import pandas as pd
from advanced_name_cleaner import AdvancedNameCleaner

# ---------- 1. 构造模拟数据 ----------
data = {
    'p_name': [
        '张三', '张山', '张珊',   # 同音组1
        '李四', '李斯',          # 同音组2
        '王五', '王武',          # 同音组3
        '赵六',                  # 正常
        '张珊', '张山'           # 重复出现
    ],
    'year': [2020, 2020, 2021, 2021, 2022, 2022, 2022, 2023, 2021, 2020],
    'company': [
        'A公司', 'A公司', 'B公司',
        'C公司', 'C公司',
        'D公司', 'D公司',
        'E公司',
        'B公司', 'A公司'
    ]
}

df_combined = pd.DataFrame(data)
print("原始数据：")
print(df_combined)

# ---------- 2. 初始化清洗器（指定辅助列） ----------
cleaner = AdvancedNameCleaner(
    aux_columns=['year', 'company'],
    threshold=0.85
)

# ---------- 3. 启动交互式清洗 ----------
df_final, mapping = cleaner.interactive_review(df_combined, name_col='p_name')

# ---------- 4. 输出结果 ----------
print("\n" + "=" * 80)
print("清洗完成！修正映射如下：")
for k, v in mapping.items():
    print(f"  '{k}' -> '{v}'")

print("\n清洗后的数据：")
print(df_final)